name: Linux

on:
  push:
    branches: [main, ci/*]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpp:
    name: C++ Optimized
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Bazelisk
        run: |
          sudo curl -fsSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel
      - name: Run tests
        run: bazel test //src/... //third_party/utf8_range/... --config=opt --test_output=errors

  upb:
    name: UPB Fastbuild
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install Bazelisk
        run: |
          sudo curl -fsSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel
      - name: Run tests
        run: bazel test //upb/... //upb_generator/... --test_output=errors
